### ISSUE TITLE
room not set / mattermost

### ISSUE THREAD

**Issue by rompic** [robhurring/hubot-redmine#23]
using this together with the mattermost adapter i get the following error in the log file:

[Sun Feb 14 2016 13:37:48 GMT+0100 (CET)] DEBUG Executing listener callback for Message 'hubot link me #10473'
[Sun Feb 14 2016 13:37:48 GMT+0100 (CET)] ERROR TypeError: Cannot read property 'room' of undefined
  at Mattermost.send (/home/mattermost/flubot/node_modules/hubot-mattermost/src/mattermost.coffee:13:42)
  at Mattermost.reply (/home/mattermost/flubot/node_modules/hubot-mattermost/src/mattermost.coffee:25:8)
  at /home/mattermost/flubot/node_modules/hubot/src/response.coffee:82:7
  at allDone (/home/mattermost/flubot/node_modules/hubot/src/middleware.coffee:41:37)
  at /home/mattermost/flubot/node_modules/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/home/mattermost/flubot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/home/mattermost/flubot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
  at /home/mattermost/flubot/node_modules/hubot/src/middleware.coffee:46:13
  at process._tickCallback (node.js:415:13)

**Comment by stephenyeargin** [comment]
Just to verify, are you up to date with the latest version of `hubot-mattermost`? Looks like they had an issue with the adapters that was resolved in December.

Reference:
https://github.com/renanvicente/hubot-mattermost/issues/11
https://github.com/renanvicente/hubot-mattermost/pull/6

**Comment by rompic** [comment]
thanks stephen. after an update everything works except
hubot add issue to abc with cde
and
hubot redmine me 1234

**Comment by stephenyeargin** [comment]
Cool. Can you spin those off into new issues if needed?
